/* Criar minha database */

CREATE DATABASE LIVRARIA;

/* Conectando-se a minha database */

USE LIVRARIA;

/* Criando a minha tabela 'Livros'*/

CREATE TABLE LIVROS(
	NOME_LIVRO VARCHAR(30),
	NUMERO_PAGS INT(4),
	ANO_LIVRO INT(4),
	UF_EDITORA CHAR(2),
	NOME_EDITORA VARCHAR(20),
	SEXO_AUTOR CHAR(1),
	VALOR_LIVRO FLOAT(5),
	NOME_AUTOR VARCHAR(30)
);

/* OLHAR TABELA */

SHOW TABLES;

/* DESCOBRINDO A ESTRUTURA DA TABELA */

DESC LIVROS;

/* INSERIR OS DADOS */

INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGS, NOME_EDITORA, VALOR_LIVRO,
UF_EDITORA, ANO_LIVRO) VALUES('Cavaleiro Real','Ana Claudia','F', 465, 'Atlas',	49.9, 'RJ',2009);

INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGS, NOME_EDITORA, VALOR_LIVRO,
UF_EDITORA, ANO_LIVRO) VALUES('SQL para leigos', 'João Nunes', 'M',	450, 'Addison',	98.0, 'SP',	2018);

INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGS, NOME_EDITORA, VALOR_LIVRO,
UF_EDITORA, ANO_LIVRO) VALUES('Receitas Caseiras', 'Celia Tavares','F', 210, 'Atlas', 45.0,'RJ', 2008);

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_LIVRO) 
VALUES ('Pessoas Efetivas', 'Eduardo Santos', 'M', 390, 'Beta', 78.99, 'RJ', 2018);

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_LIVRO) 
VALUES ('Hábitos Saudáveis', 'Eduardo Santos', 'M', 630, 'Beta', 150.98, 'RJ', 2019);

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_LIVRO) 
VALUES ('A Casa Marrom', 'Hermes Macedo', 'M', 250, 'Bubba', 60.00, 'MG', 2016);

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_LIVRO) 
VALUES ('Estacio Querido', 'Geraldo Francisco',	'M', 310, 'Insignia', 100.0, 'ES', 2015);

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_LIVRO) 
VALUES ('Pra sempre amigas', 'Leda Silva', 'F',	 510, 'Insignia', 78.98, 'ES', 2011);

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_LIVRO) 
VALUES ('Copas Inesqueciveis',	'Marco Alcantara', 'M',	200, 'Larson',	130.98,	'RS',2018);

INSERT INTO LIVROS (NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, NUMERO_PAGS, NOME_EDITORA, VALOR_LIVRO, UF_EDITORA, ANO_LIVRO) 
VALUES ('O poder da mente',	'Clara Mafra', 'F',	120, 'Continental',	56.58, 'SP', 2017);

/* 1- Trazer TODOS os dados */

SELECT * FROM LIVROS;

/* 2- Trazer NOME DO LIVRO e NOME DA EDITORA */

SELECT NOME_LIVRO, NOME_EDITORA FROM LIVROS;

/* 3- Trazer NOME DO LIVRO e UF DO LIVRO de autores do sexo MASCULINO */

SELECT NOME_LIVRO, UF_EDITORA FROM LIVROS
WHERE SEXO_AUTOR = 'M';

/* 4- Trazer NOME DO LIVRO e NUMERO DE PAGS de autores do sexo FEMININO */

SELECT NOME_LIVRO, NUMERO_PAGS FROM LIVROS
WHERE SEXO_AUTOR = 'F';

/* 5- Trazer os valores dos livros feitos em São Paulo */

SELECT VALOR_LIVRO FROM LIVROS
WHERE UF_EDITORA = 'SP';

/* 6- Trazer dados dos autores MASCULINOS que tiveram livros publicados por são paulo ou rio de janeiro */

SELECT * FROM LIVROS
WHERE SEXO_AUTOR = 'M' AND UF_EDITORA IN ('SP', 'RJ');


